<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Naveenkumar" ignored="0" name="Runner" tests="9" failures="5" timestamp="31 Dec 2021 06:30:49 GMT" time="180.34" errors="0">
  <testcase name="runScenario" time="36.271" classname="io.cucumber.testng.AbstractTestNGCucumberTests">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.coding.StepDefinitions.StepDefinition.for_valid_credendtial_login_successfully_else_fail_with_an_expected_error(StepDefinition.java:91)
at ✽.for valid credendtial login successfully else fail with an expected error(file:///F:/Practicesession/Logitech_Testng_Cucumber/src/test/resources/com/coding/features/Feature1.feature:8)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase name="runScenario" time="22.056" classname="io.cucumber.testng.AbstractTestNGCucumberTests">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.coding.StepDefinitions.StepDefinition.for_valid_credendtial_login_successfully_else_fail_with_an_expected_error(StepDefinition.java:91)
at ✽.for valid credendtial login successfully else fail with an expected error(file:///F:/Practicesession/Logitech_Testng_Cucumber/src/test/resources/com/coding/features/Feature1.feature:8)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase name="runScenario" time="22.612" classname="io.cucumber.testng.AbstractTestNGCucumberTests">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.coding.StepDefinitions.StepDefinition.for_valid_credendtial_login_successfully_else_fail_with_an_expected_error(StepDefinition.java:91)
at ✽.for valid credendtial login successfully else fail with an expected error(file:///F:/Practicesession/Logitech_Testng_Cucumber/src/test/resources/com/coding/features/Feature1.feature:8)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase name="runScenario" time="29.076" classname="io.cucumber.testng.AbstractTestNGCucumberTests">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.coding.StepDefinitions.StepDefinition.for_valid_credendtial_login_successfully_else_fail_with_an_expected_error(StepDefinition.java:91)
at ✽.for valid credendtial login successfully else fail with an expected error(file:///F:/Practicesession/Logitech_Testng_Cucumber/src/test/resources/com/coding/features/Feature1.feature:8)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase name="runScenario" time="14.203" classname="io.cucumber.testng.AbstractTestNGCucumberTests">
    <failure type="java.lang.AssertionError" message="Dynamic Loading click Failed, Validate expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Dynamic Loading click Failed, Validate expected [true] but found [false]
at com.coding.StepDefinitions.StepDefinition.user_launches_the_application_and_clicks_on_something(StepDefinition.java:73)
at ✽.User launches the application and clicks on "Dynamic Loading"(file:///F:/Practicesession/Logitech_Testng_Cucumber/src/test/resources/com/coding/features/Feature1.feature:19)
... Removed 3 stack frames]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase name="runScenario" time="9.145" classname="io.cucumber.testng.AbstractTestNGCucumberTests"/>
  <testcase name="runScenario" time="15.174" classname="io.cucumber.testng.AbstractTestNGCucumberTests"/>
  <testcase name="runScenario" time="20.715" classname="io.cucumber.testng.AbstractTestNGCucumberTests"/>
  <testcase name="runScenario" time="9.106" classname="io.cucumber.testng.AbstractTestNGCucumberTests"/>
</testsuite> <!-- Runner -->
