<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Naveenkumar" name="com.coding.Runner.TestRunner" tests="9" failures="1" timestamp="31 Dec 2021 06:30:49 GMT" time="178.358" errors="4">
  <testcase name="runScenario" time="15.174" classname="com.coding.Runner.TestRunner"/>
  <testcase name="runScenario" time="9.106" classname="com.coding.Runner.TestRunner"/>
  <testcase name="runScenario" time="20.715" classname="com.coding.Runner.TestRunner"/>
  <testcase name="runScenario" time="22.056" classname="com.coding.Runner.TestRunner">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.coding.StepDefinitions.StepDefinition.for_valid_credendtial_login_successfully_else_fail_with_an_expected_error(StepDefinition.java:91)
at ✽.for valid credendtial login successfully else fail with an expected error(file:///F:/Practicesession/Logitech_Testng_Cucumber/src/test/resources/com/coding/features/Feature1.feature:8)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <testcase name="runScenario" time="9.145" classname="com.coding.Runner.TestRunner"/>
  <testcase name="runScenario" time="22.612" classname="com.coding.Runner.TestRunner">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.coding.StepDefinitions.StepDefinition.for_valid_credendtial_login_successfully_else_fail_with_an_expected_error(StepDefinition.java:91)
at ✽.for valid credendtial login successfully else fail with an expected error(file:///F:/Practicesession/Logitech_Testng_Cucumber/src/test/resources/com/coding/features/Feature1.feature:8)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <testcase name="runScenario" time="36.271" classname="com.coding.Runner.TestRunner">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.coding.StepDefinitions.StepDefinition.for_valid_credendtial_login_successfully_else_fail_with_an_expected_error(StepDefinition.java:91)
at ✽.for valid credendtial login successfully else fail with an expected error(file:///F:/Practicesession/Logitech_Testng_Cucumber/src/test/resources/com/coding/features/Feature1.feature:8)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <testcase name="runScenario" time="29.076" classname="com.coding.Runner.TestRunner">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.coding.StepDefinitions.StepDefinition.for_valid_credendtial_login_successfully_else_fail_with_an_expected_error(StepDefinition.java:91)
at ✽.for valid credendtial login successfully else fail with an expected error(file:///F:/Practicesession/Logitech_Testng_Cucumber/src/test/resources/com/coding/features/Feature1.feature:8)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <testcase name="runScenario" time="14.203" classname="com.coding.Runner.TestRunner">
    <failure type="java.lang.AssertionError" message="Dynamic Loading click Failed, Validate expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Dynamic Loading click Failed, Validate expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at com.coding.StepDefinitions.StepDefinition.user_launches_the_application_and_clicks_on_something(StepDefinition.java:73)
at ✽.User launches the application and clicks on "Dynamic Loading"(file:///F:/Practicesession/Logitech_Testng_Cucumber/src/test/resources/com/coding/features/Feature1.feature:19)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- com.coding.Runner.TestRunner -->
